### ISSUE TITLE
transform() method is actually fit_transform() (almost)

### ISSUE THREAD

**Issue by apyskir** [neptune-ml/steps#4]
Looking at this for loop: https://github.com/neptune-ml/steps/blob/dev/steps/base.py#L151.
If one has a pipeline, then calling transform() on the last Step of the pipeline differs only slightly with calling fit_transform(), because in both cases all input Steps (and their inputs, etc.) are fitted and then they transform data. The only difference is that the last Step is not fitted.
I think that calling transform() on the last Step of the pipeline should call transform() methods of the input Steps, and yield error or inform the User if one of the input Steps is not saved in ./transformers directory.
What do you think about this idea?

**Comment by kamil-kaczmarek** [comment]
@apyskir merged in #9 Thanks!
